"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { AlertTriangle, ArrowLeft, Check, CircleStop, ExternalLink, LockKeyhole, Play, ShieldCheck, ShieldX, Sparkles } from "lucide-react";
import Link from "next/link";
import type { NegotiationTurn, TermValue } from "@/lib/negotiation/types";
import { WalletProof } from "./wallet-proof";

interface DemoResponse { turns: NegotiationTurn[]; converged: boolean; finalTerms?: Record<string, TermValue>; gapSummary?: string; source: "deterministic" | "deterministic-fallback" | "groq-live" | "mixed-fallback"; liveAgentCalls?: number; }

export function NegotiationLab() {
  const [result,setResult]=useState<DemoResponse|null>(null); const [running,setRunning]=useState(false); const [scenario,setScenario]=useState<"standard"|"deadlock">("standard"); const [error,setError]=useState(""); const [challenge,setChallenge]=useState<{blocked:boolean;violations:Array<{reason:string}>}|null>(null);
  async function run(){setRunning(true);setResult(null);setError("");setChallenge(null);try{const response=await fetch("/api/negotiate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scenario})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Negotiation failed");setResult(body)}catch(reason){setError(reason instanceof Error?reason.message:"Negotiation failed")}finally{setRunning(false)}}
  async function attackGuardrail(){const response=await fetch("/api/guardrails/challenge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({terms:{annualPrice:99000,contractMonths:36,paymentDays:7,supportHours:2,autoRenewal:true}})});setChallenge(await response.json())}
  return <main className="lab-shell">
    <header className="lab-topbar"><Link href="/"><ArrowLeft size={17}/> AccordOS</Link><div><span className="status-dot"/> Live Groq agents Â· Solana devnet</div><Link href="/verify">Public verifier <ExternalLink size={14}/></Link></header>
    <section className="lab-heading"><div><span className="eyebrow dark-eye">LIVE NEGOTIATION ROOM</span><h1>Northstar Ã— Helio</h1><p>SaaS subscription renewal Â· Private two-sided authority</p></div><div className="lab-controls"><div className="scenario-switch"><button className={scenario==="standard"?"active":""} onClick={()=>setScenario("standard")} disabled={running}>Convergence</button><button className={scenario==="deadlock"?"active":""} onClick={()=>setScenario("deadlock")} disabled={running}>Deadlock test</button></div><button className="button" onClick={run} disabled={running}>{running?<CircleStop className="spin" size={17}/>:<Play size={17}/>} {running?"Agents negotiatingâ€¦":"Start both agents"}</button></div></section>
    <section className="lab-grid">
      <aside className="constraint-panel"><div className="panel-title"><LockKeyhole size={16}/><span>Northstar private authority</span></div><p>The deadlock test lowers the hidden buyer ceiling below the vendor floor.</p>{[["Annual price",scenario==="deadlock"?"â‰¤ $38,000":"â‰¤ $45,000","Critical"],["Contract term","â‰¤ 24 months","High"],["Payment terms","â‰¥ Net 30","Flexible"],["Support","â‰¥ 20 hrs/mo","High"]].map(([label,value,priority])=><div className="constraint-row" key={label}><span>{label}<small>{priority}</small></span><b>{value}</b></div>)}<div className="hard-term"><ShieldCheck size={15}/><span><b>Hard requirement</b>No automatic renewal</span></div><button className="attack-button" onClick={attackGuardrail}><ShieldX size={14}/> Attempt $99,000 override</button>{challenge&&<motion.div className="challenge-result" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><b><Check size={13}/> Override blocked</b><small>{challenge.violations.length} authority violations detected</small></motion.div>}</aside>
      <div className="transcript-panel"><div className="panel-title"><span>Shared agent transcript</span><span className="source-tag"><Sparkles size={13}/> {result?`${result.liveAgentCalls??0}/${result.turns.length} live Groq turns`:"Ready"}</span></div>{!result&&!running&&<div className="lab-empty"><span className="orb"><i/><i/></span><h2>{scenario==="standard"?"Overlapping authority loaded":"Impossible price gap loaded"}</h2><p>{scenario==="standard"?"Run independent agents through validation and convergence.":"Prove the engine escalates instead of inventing an unauthorized deal."}</p></div>}{running&&<div className="lab-empty"><span className="scan-orb"/><h2>Two agents are negotiating</h2><p>Each call receives its own private constraints plus only shared history.</p></div>}{error&&<div className="lab-empty"><h2>Negotiation stopped</h2><p>{error}</p></div>}<AnimatePresence>{result&&<motion.div className="turn-list" initial={{opacity:0}} animate={{opacity:1}}>{result.turns.map((turn,index)=><motion.article className={`lab-turn ${turn.side}`} key={turn.id} initial={{opacity:0,y:20,scale:.98}} animate={{opacity:1,y:0,scale:1}} transition={{delay:index*.16}}><div><span className={`avatar ${turn.side==="buyer"?"dark":"lime"}`}>{turn.company[0]}</span><p><b>{turn.company} agent</b><small>Round {turn.round} Â· {turn.type}</small></p><span className="validated"><Check size={12}/> Code validated</span></div><p>{turn.reasoning}</p><div className="term-chips"><span>${Number(turn.terms.annualPrice).toLocaleString()}</span><span>{String(turn.terms.contractMonths)} months</span><span>Net {String(turn.terms.paymentDays)}</span><span>{String(turn.terms.supportHours)} support hrs</span></div><small className="model-stamp">Generated by {turn.generatedBy==="groq"?"Groq Llama 3.3 70B":"safe deterministic fallback"}</small></motion.article>)}</motion.div>}</AnimatePresence></div>
      <aside className="agreement-panel"><div className="panel-title"><span>Agreement and proof</span></div>{!result?<div className="agreement-wait"><span>{running?"â€¢â€¢":"00"}</span><p>Validated rounds</p><small>No terms become final without both profiles and both humans passing.</small></div>:!result.converged?<motion.div className="deadlock-card" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}}><span><AlertTriangle/></span><h2>Deadlock escalated</h2><p>No authorized price satisfies both organizations. AccordOS stopped instead of fabricating agreement.</p><small>{result.gapSummary}</small></motion.div>:<><div className="success-seal"><Check size={22}/></div><h2>Common ground found</h2><p className="muted">The final proposal passes both private constraint profiles.</p><dl className="final-terms"><div><dt>Annual price</dt><dd>${Number(result.finalTerms?.annualPrice).toLocaleString()}</dd></div><div><dt>Contract term</dt><dd>{String(result.finalTerms?.contractMonths)} months</dd></div><div><dt>Payment</dt><dd>Net {String(result.finalTerms?.paymentDays)}</dd></div><div><dt>Renewal</dt><dd>Explicit approval</dd></div></dl>{result.finalTerms&&<WalletProof terms={result.finalTerms}/>}</>}</aside>
    </section>
  </main>;
}

