"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowLeft, Check, CircleStop, ExternalLink, Fingerprint, LockKeyhole, Play, ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";
import type { NegotiationTurn, TermValue } from "@/lib/negotiation/types";
import { WalletProof } from "./wallet-proof";

interface DemoResponse {
  turns: NegotiationTurn[];
  converged: boolean;
  finalTerms?: Record<string, TermValue>;
  source: "deterministic" | "deterministic-fallback" | "groq-live";
}

export function NegotiationLab() {
  const [result, setResult] = useState<DemoResponse | null>(null);
  const [running, setRunning] = useState(false);
  const [approvals, setApprovals] = useState(0);
  const [error, setError] = useState("");

  async function run() {
    setRunning(true); setResult(null); setApprovals(0); setError("");
    try {
      const response = await fetch("/api/negotiate", { method: "POST" });
      const body = await response.json();
      if (!response.ok) throw new Error(body.error ?? "Negotiation failed");
      setResult(body);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Negotiation failed"); }
    finally { setRunning(false); }
  }

  return <main className="lab-shell">
    <header className="lab-topbar"><Link href="/"><ArrowLeft size={17} /> AccordOS</Link><div><span className="status-dot" /> Live Groq agents · Solana devnet</div><Link href="/dashboard">Analytics <ExternalLink size={14} /></Link></header>
    <section className="lab-heading"><div><span className="eyebrow dark-eye">LIVE NEGOTIATION ROOM</span><h1>Northstar × Helio</h1><p>SaaS subscription renewal · Maximum 12 rounds</p></div><button className="button" onClick={run} disabled={running}>{running ? <CircleStop className="spin" size={17} /> : <Play size={17} />}{running ? "Two agents negotiating…" : result ? "Run fresh negotiation" : "Start both agents"}</button></section>
    <section className="lab-grid">
      <aside className="constraint-panel"><div className="panel-title"><LockKeyhole size={16} /><span>Northstar private authority</span></div><p>Only the buyer agent and deterministic validator receive these limits. They never enter the shared transcript.</p>{[["Annual price", "≤ $45,000", "Critical"],["Contract term", "≤ 24 months", "High"],["Payment terms", "≥ Net 30", "Flexible"],["Support", "≥ 20 hrs/mo", "High"]].map(([label,value,priority]) => <div className="constraint-row" key={label}><span>{label}<small>{priority}</small></span><b>{value}</b></div>)}<div className="hard-term"><ShieldCheck size={15} /><span><b>Hard requirement</b>No automatic renewal</span></div><div className="privacy-note"><Fingerprint size={18} /><span><b>Fail-closed authority</b>Malformed or out-of-bound offers are structurally rejected.</span></div></aside>
      <div className="transcript-panel"><div className="panel-title"><span>Shared agent transcript</span><span className="source-tag"><Sparkles size={13} /> {result?.source === "groq-live" ? "Two live Groq agents" : "Ready for live agents"}</span></div>{!result && !running && <div className="lab-empty"><span className="orb"><i /><i /></span><h2>Private authority loaded</h2><p>Start both agents. Every round is independently generated and validated before entering this transcript.</p></div>}{running && <div className="lab-empty"><span className="scan-orb" /><h2>Two agents are negotiating</h2><p>Buyer and vendor calls receive separate private constraints plus only the shared history.</p></div>}{error && <div className="lab-empty"><h2>Negotiation stopped</h2><p>{error}</p></div>}<AnimatePresence>{result && <motion.div className="turn-list" initial={{opacity:0}} animate={{opacity:1}}>{result.turns.map((turn,index) => <motion.article className={`lab-turn ${turn.side}`} key={turn.id} initial={{opacity:0,y:20,scale:.98}} animate={{opacity:1,y:0,scale:1}} transition={{delay:index*.18}}><div><span className={`avatar ${turn.side === "buyer" ? "dark" : "lime"}`}>{turn.company[0]}</span><p><b>{turn.company} agent</b><small>Round {turn.round} · {turn.type}</small></p><span className="validated"><Check size={12} /> Code validated</span></div><p>{turn.reasoning}</p><div className="term-chips"><span>${Number(turn.terms.annualPrice).toLocaleString()}</span><span>{String(turn.terms.contractMonths)} months</span><span>Net {String(turn.terms.paymentDays)}</span><span>{String(turn.terms.supportHours)} support hrs</span></div><small className="model-stamp">Generated by {turn.generatedBy === "groq" ? "Groq Llama 3.3 70B" : "deterministic fallback"}</small></motion.article>)}</motion.div>}</AnimatePresence></div>
      <aside className="agreement-panel"><div className="panel-title"><span>Agreement and proof</span></div>{!result?.converged ? <div className="agreement-wait"><span>{running ? "••" : "00"}</span><p>Validated rounds</p><small>No terms become final without approval from both organizations.</small></div> : <><div className="success-seal"><Check size={22} /></div><h2>Common ground found</h2><p className="muted">The final proposal passes both organizations&apos; private constraints.</p><dl className="final-terms"><div><dt>Annual price</dt><dd>${Number(result.finalTerms?.annualPrice).toLocaleString()}</dd></div><div><dt>Contract term</dt><dd>{String(result.finalTerms?.contractMonths)} months</dd></div><div><dt>Payment</dt><dd>Net {String(result.finalTerms?.paymentDays)}</dd></div><div><dt>Renewal</dt><dd>Explicit approval</dd></div></dl><div className="approval-stack"><button onClick={() => setApprovals(Math.max(approvals,1))} className={approvals >= 1 ? "approved" : ""}><span>Northstar human approval</span>{approvals >= 1 ? <Check size={15} /> : "Approve"}</button><button onClick={() => setApprovals(2)} disabled={approvals < 1} className={approvals >= 2 ? "approved" : ""}><span>Helio human approval</span>{approvals >= 2 ? <Check size={15} /> : "Approve"}</button></div>{result.finalTerms && <WalletProof terms={result.finalTerms} ready={approvals === 2} />}</>}</aside>
    </section>
  </main>;
}
