"use client";

import { useEffect, useState } from "react";
import bs58 from "bs58";
import { Connection, PublicKey, Transaction } from "@solana/web3.js";
import { Check, Download, ExternalLink, Fingerprint, KeyRound, LoaderCircle, LogOut, PlugZap, ShieldCheck, Wallet } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import type { TermValue } from "@/lib/negotiation/types";
import { createReceipt } from "@/lib/solana/receipt";

interface Approval { role: "buyer" | "vendor"; publicKey: string; signature: string }

export function WalletProof({ terms, negotiationId }: { terms: Record<string, TermValue>; negotiationId: string }) {
  const [address,setAddress]=useState(""); const [balance,setBalance]=useState<number|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [approvals,setApprovals]=useState<Approval[]>([]); const [proof,setProof]=useState<{hash:string;signature:string;verified:boolean;slot?:number}|null>(null);
  const provider=()=>window.solana??window.solflare;
  useEffect(()=>{const wallet=provider();if(wallet?.publicKey)void setConnectedWallet(wallet.publicKey.toString())},[]);
  async function setConnectedWallet(publicKey:string){setAddress(publicKey);const connection=new Connection("https://api.devnet.solana.com","confirmed");setBalance((await connection.getBalance(new PublicKey(publicKey)))/1_000_000_000)}
  async function connect(){setError("");const wallet=provider();if(!wallet){setError("Install Phantom or Solflare, switch it to devnet, then reload.");return}try{await setConnectedWallet((await wallet.connect()).publicKey.toString())}catch(reason){setError(reason instanceof Error?reason.message:"Wallet connection was cancelled")}}
  async function disconnect(){await provider()?.disconnect();setAddress("");setBalance(null);setError("")}
  async function signApproval(role:"buyer"|"vendor"){
    const wallet=provider();if(!wallet||!address)return;setBusy(true);setError("");
    try{if(approvals.some((item)=>item.publicKey===address))throw new Error("Switch to a different wallet for the other organization");const challenge=await fetch("/api/approvals/challenge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({terms,role,negotiationId})}).then((item)=>item.json());const signed=await wallet.signMessage(new TextEncoder().encode(challenge.message),"utf8");const approval={role,publicKey:signed.publicKey.toString(),signature:bs58.encode(signed.signature)};const verified=await fetch("/api/approvals/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({terms,approval,negotiationId})}).then((item)=>item.json());if(!verified.valid)throw new Error("Wallet signature verification failed");setApprovals((current)=>[...current.filter((item)=>item.role!==role),approval]);await disconnect()}catch(reason){setError(reason instanceof Error?reason.message:"Approval signing failed")}finally{setBusy(false)}}
  async function requestAirdrop(){if(!address)return;setBusy(true);setError("");try{const connection=new Connection("https://api.devnet.solana.com","confirmed");const signature=await connection.requestAirdrop(new PublicKey(address),.05*1_000_000_000);await connection.confirmTransaction(signature,"confirmed");await setConnectedWallet(address)}catch{setError("Public faucet rate-limited the request. Use faucet.solana.com.")}finally{setBusy(false)}}
  async function anchor(){const wallet=provider();if(!wallet||!address)return;setBusy(true);setError("");try{const response=await fetch("/api/proof",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({terms,approvals,walletAddress:address,negotiationId})});const prepared=await response.json();if(!response.ok)throw new Error(prepared.error);const signed=await wallet.signAndSendTransaction(Transaction.from(Buffer.from(prepared.transaction,"base64")));const connection=new Connection("https://api.devnet.solana.com","confirmed");await connection.confirmTransaction(signed.signature,"confirmed");const verification=await fetch("/api/proof/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({signature:signed.signature,hash:prepared.hash})}).then((item)=>item.json());setProof({hash:prepared.hash,signature:signed.signature,verified:verification.verified,slot:verification.slot})}catch(reason){setError(reason instanceof Error?reason.message:"Devnet transaction failed")}finally{setBusy(false)}}
  const nextRole:"buyer"|"vendor"=approvals.some((item)=>item.role==="buyer")?"vendor":"buyer";
  return <motion.div className="wallet-proof dual-proof" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><div className="signature-progress">{(["buyer","vendor"] as const).map((role)=><div className={approvals.some((item)=>item.role===role)?"signed":""} key={role}><span>{approvals.some((item)=>item.role===role)?<Check size={13}/>:<KeyRound size={13}/>}</span><p><b>{role==="buyer"?"Northstar":"Helio"}</b><small>{approvals.find((item)=>item.role===role)?.publicKey.slice(0,8)??"Signature required"}</small></p></div>)}</div>{!address?<button className="wallet-connect" onClick={connect}><Wallet size={16}/><span><b>{approvals.length===2?"Connect fee-paying wallet":`Connect ${nextRole} wallet`}</b><small>Phantom or Solflare · Devnet</small></span><PlugZap size={15}/></button>:<div className="wallet-connected"><span><i/><b>{address.slice(0,4)}…{address.slice(-4)}</b><small>{balance?.toFixed(4)??"…"} DEVNET SOL</small></span><button aria-label="Disconnect wallet" onClick={disconnect}><LogOut size={14}/></button><ShieldCheck size={17}/></div>}<AnimatePresence mode="wait">{address&&approvals.length<2&&<motion.button className="approval-sign-button" key={nextRole} initial={{opacity:0,y:7}} animate={{opacity:1,y:0}} exit={{opacity:0}} disabled={busy} onClick={()=>signApproval(nextRole)}>{busy?<LoaderCircle className="spin" size={15}/>:<KeyRound size={15}/>} Sign as {nextRole==="buyer"?"Northstar buyer":"Helio vendor"}</motion.button>}</AnimatePresence>{address&&balance===0&&approvals.length===2&&<button className="wallet-airdrop" disabled={busy} onClick={requestAirdrop}>Request 0.05 devnet SOL</button>}{address&&approvals.length===2&&!proof&&<button className="button proof-button" disabled={busy||balance===0} onClick={anchor}>{busy?<LoaderCircle className="spin" size={16}/>:<Fingerprint size={16}/>} {busy?"Signing and verifying…":"Anchor dual-approved proof"}</button>}{proof&&<><button className="receipt-download" onClick={()=>{const receipt=createReceipt(negotiationId,terms,approvals,proof.signature);const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([JSON.stringify(receipt,null,2)],{type:"application/json"}));link.download=`accordos-receipt-${proof.hash.slice(0,10)}.json`;link.click();URL.revokeObjectURL(link.href)}}><Download size={13}/> Download verifiable receipt</button><div className={proof.verified?"proof-card verified-proof":"proof-card"}><b>{proof.verified?<><Check size={13}/> Verified dual-approved proof</>:"Proof pending"}</b><code>{proof.signature}</code><span>Hash {proof.hash.slice(0,12)}… · Slot {proof.slot??"pending"}</span><a target="_blank" rel="noreferrer" href={`https://explorer.solana.com/tx/${proof.signature}?cluster=devnet`}>Open Solana Explorer <ExternalLink size={12}/></a></div></>}{error&&<p className="wallet-error">{error}</p>}</motion.div>;
}





